name: Run Local Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
    defaults:
      run:
        working-directory: ./code/TodoApp

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace

    - name: Run JVM Unit Tests
      run: ./gradlew testDebug --stacktrace
