name: Run Instrumental Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  androidTest:
    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
    defaults:
      run:
        working-directory: ./code/TodoApp
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [24, 30]

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86_64
        disable-animations: true
        working-directory: ./code/TodoApp
        script: ./gradlew connectedCheck --stacktrace
